// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260924143320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Data.InventoryStep", b =>
                {
                    b.Property<Guid>("SagaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Step")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RejectedSku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SagaId", "Step");

                    b.ToTable("Steps", "inventory");
                });

            modelBuilder.Entity("Inventory.Data.Reservation", b =>
                {
                    b.Property<Guid>("SagaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("SagaId", "OrderLineId");

                    b.ToTable("Reservations", "inventory");
                });

            modelBuilder.Entity("Inventory.Data.StockItem", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.HasKey("Sku");

                    b.ToTable("Stock", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Available_NonNegative", "[Available] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Sku = "BOOK-DDD",
                            Available = 1000
                        },
                        new
                        {
                            Sku = "BOOK-EIP",
                            Available = 1000
                        },
                        new
                        {
                            Sku = "MUG-SAGA",
                            Available = 50
                        },
                        new
                        {
                            Sku = "LIMITED-01",
                            Available = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
