// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.Data;

#nullable disable

namespace Orders.Data.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260924144550_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.Saga.CheckoutSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AwaitingInquiry")
                        .HasColumnType("bit");

                    b.Property<string>("CaptureId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CardToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CheckoutSagas", "orders");
                });

            modelBuilder.Entity("Orders.Saga.CheckoutSaga", b =>
                {
                    b.OwnsMany("Contracts.OrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("CheckoutSagaId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("OrderLineId");

                            b1.Property<int>("Quantity");

                            b1.Property<string>("Sku")
                                .IsRequired();

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2);

                            b1.HasKey("CheckoutSagaId", "__synthesizedOrdinal");

                            b1.ToTable("CheckoutSagas", "orders");

                            b1
                                .ToJson("Lines")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CheckoutSagaId");
                        });

                    b.OwnsMany("Orders.Saga.JournalEntry", "Journal", b1 =>
                        {
                            b1.Property<Guid>("CheckoutSagaId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Outcome")
                                .IsRequired();

                            b1.Property<string>("Reference");

                            b1.Property<string>("Step")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("UpdatedUtc");

                            b1.HasKey("CheckoutSagaId", "__synthesizedOrdinal");

                            b1.ToTable("CheckoutSagas", "orders");

                            b1
                                .ToJson("Journal")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CheckoutSagaId");
                        });

                    b.Navigation("Journal");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
